# Generated by Django 5.2 on 2025-05-10 06:47

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loan_installment', models.BooleanField(default=False)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_installments', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('sheba_number', models.CharField(blank=True, max_length=35, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('manager_approval', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('ceo_approval', models.BooleanField(default=False)),
                ('final_approval', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'AssistanceRequest',
                'verbose_name_plural': 'AssistanceRequest',
                'ordering': ('-request_date',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('sheba_number', models.CharField(blank=True, max_length=35, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'BankAccount',
                'verbose_name_plural': 'BankAccount',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('leave_type', models.CharField(blank=True, choices=[('entitlement', 'استحقاقی'), ('illness', 'استعلاجی'), ('without_pay', 'بدون حقوق')], max_length=20, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('hourly', 'ساعتی'), ('daily', 'روزانه')], max_length=20, null=True)),
                ('hourly_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('manager_approval', models.BooleanField(default=False)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('admin_approval', models.BooleanField(default=False)),
                ('ceo_approval', models.BooleanField(default=False)),
                ('ceo_reject_reason', models.TextField(blank=True, null=True)),
                ('final_approval', models.BooleanField(default=False)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'LeaveRequest',
                'verbose_name_plural': 'LeaveRequests',
                'ordering': ('-request_date',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyAssistanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_assistance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'MonthlyAssistanceSummary',
                'verbose_name_plural': 'MonthlyAssistanceSummary',
                'ordering': ('-create_at',),
            },
        ),
    ]
