# Generated by Django 5.2 on 2025-05-08 06:42

import django.db.models.deletion
import human_resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worklog', '0011_externalperson_register_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fingerprint_image', models.ImageField(blank=True, null=True, upload_to=human_resources.models.fingerprint_upload_path)),
                ('loan_installment', models.BooleanField(default=False)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_installments', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('sheba_number', models.CharField(blank=True, max_length=30, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('manager_approval', models.BooleanField(default=False)),
                ('admin_approval', models.BooleanField(default=False)),
                ('ceo_approval', models.BooleanField(default=False)),
                ('final_approval', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'AssistanceRequest',
                'verbose_name_plural': 'AssistanceRequest',
                'ordering': ('-request_date',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('sheba_number', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'BankAccount',
                'verbose_name_plural': 'BankAccount',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyAssistanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_assistance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'MonthlyAssistanceSummary',
                'verbose_name_plural': 'MonthlyAssistanceSummary',
                'ordering': ('-create_at',),
            },
        ),
    ]
