# Generated by Django 5.2 on 2025-05-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
        ('worklog', '0002_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeaveSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_leave', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.employee')),
            ],
            options={
                'verbose_name': 'MonthlyLeaveSummary',
                'verbose_name_plural': 'MonthlyLeaveSummaries',
                'ordering': ('-create_at',),
            },
        ),
    ]
