# Generated by Django 5.2 on 2025-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
