# Generated by Django 5.2 on 2025-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_alter_assistancerequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
