# Generated by Django 5.2 on 2025-05-10 08:23

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_monthlyleavesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
