# Generated by Django 5.2 on 2025-05-10 09:05

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_leaverequest_end_date_leaverequest_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='hourly_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
