# Generated by Django 5.2 on 2025-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_alter_assistancerequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
