# Generated by Django 5.2 on 2025-05-10 09:06

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_leaverequest_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='hourly_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
