# Generated by Django 5.2 on 2025-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_bankaccount_sheba_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='request_date',
            field=models.DateField(),
        ),
    ]
