# Generated by Django 5.2 on 2025-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_alter_leaverequest_hourly_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyleavesummary',
            name='leave_requests_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
