# Generated by Django 5.2 on 2025-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_alter_assistancerequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
