# Generated by Django 5.2 on 2025-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_monthlyleavesummary_leave_requests_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyassistancesummary',
            name='assistance_requests_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
