# Generated by Django 5.2 on 2025-05-08 09:06

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_alter_assistancerequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyassistancesummary',
            name='total_assistance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
