# Generated by Django 5.2 on 2025-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_monthlyassistancesummary_assistance_requests_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='ceo_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
