# Generated by Django 5.2 on 2025-05-08 09:07

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_bankaccount_created_alter_assistancerequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
