# Generated by Django 5.2 on 2025-05-08 09:09

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_alter_bankaccount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
    ]
