# Generated by Django 5.2 on 2025-05-08 09:10

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_alter_bankaccount_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created_att',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
    ]
