# Generated by Django 5.2 on 2025-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='paid_installments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
