# Generated by Django 5.2 on 2025-05-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_bankaccount_created_att_alter_bankaccount_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='created_att',
        ),
    ]
