# Generated by Django 5.2 on 2025-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_alter_assistancerequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='paid_installments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
