# Generated by Django 5.2 on 2025-05-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0011_alter_assistancerequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistancerequest',
            options={'ordering': ('-create_at',), 'verbose_name': 'AssistanceRequest', 'verbose_name_plural': 'AssistanceRequest'},
        ),
    ]
