# Generated by Django 5.2 on 2025-05-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0012_alter_assistancerequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistancerequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'AssistanceRequest', 'verbose_name_plural': 'AssistanceRequest'},
        ),
        migrations.RenameField(
            model_name='assistancerequest',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
