# Generated by Django 5.2 on 2025-05-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0013_alter_assistancerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyleavesummary',
            options={'ordering': ('-created_at',), 'verbose_name': 'MonthlyLeaveSummary', 'verbose_name_plural': 'MonthlyLeaveSummaries'},
        ),
        migrations.RenameField(
            model_name='monthlyleavesummary',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
