# Generated by Django 5.2 on 2025-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0014_alter_monthlyleavesummary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='admin_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='ceo_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
