# Generated by Django 5.2 on 2025-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0015_alter_leaverequest_admin_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='manager_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
