# Generated by Django 5.2 on 2025-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0016_alter_leaverequest_manager_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='ceo_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='manager_approval',
            field=models.BooleanField(default=False),
        ),
    ]
