# Generated by Django 5.2 on 2025-05-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0017_alter_leaverequest_admin_approval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'LeaveRequest', 'verbose_name_plural': 'LeaveRequests'},
        ),
    ]
