# Generated by Django 5.2 on 2025-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0018_alter_leaverequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name_account_holder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
