# Generated by Django 5.2 on 2025-05-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
