# Generated by Django 5.2 on 2025-05-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otp_request_count_otprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprequest',
            name='user',
        ),
        migrations.AddField(
            model_name='otprequest',
            name='otp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.otp'),
        ),
    ]
