# Generated by Django 5.2 on 2025-05-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_otprequest_user_otprequest_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'USER', 'verbose_name_plural': 'USER'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTP'},
        ),
        migrations.AlterModelOptions(
            name='otprequest',
            options={'verbose_name': 'OTPRequest', 'verbose_name_plural': 'OTPRequest'},
        ),
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'ProfileUser', 'verbose_name_plural': 'ProfileUser'},
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='otp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.otp'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
