# Generated by Django 5.2 on 2025-05-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_full_name_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('employee', 'Employee'), ('guard', 'Guard'), ('user', 'User')], max_length=20, null=True),
        ),
    ]
