# Generated by Django 5.2 on 2025-05-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profileuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('employee', 'Employee'), ('guard', 'Guard'), ('user', 'User')], default='user', max_length=20, null=True),
        ),
    ]
