# Generated by Django 5.2 on 2025-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('employee', 'Employee'), ('manager', 'Manager'), ('guard', 'Guard'), ('user', 'User')], default='user', max_length=20, null=True),
        ),
    ]
