# Generated by Django 5.2 on 2025-05-10 07:19

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
