# Generated by Django 5.2 on 2025-05-06 11:34

import django.db.models.deletion
import django.utils.timezone
import worklog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_alter_loginglog_options_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('created_time',), 'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('position', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=worklog.models.avatar_upload_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.department', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'ordering': ('created_at',),
            },
        ),
    ]
