# Generated by Django 5.2 on 2025-05-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='created_by',
            new_name='user',
        ),
    ]
