# Generated by Django 5.2 on 2025-05-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0003_alter_department_options_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-created_time',), 'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-created_at',), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.department', verbose_name='department'),
        ),
    ]
