# Generated by Django 5.2 on 2025-05-19 10:56

import worklog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0005_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[worklog.models.validate_national_code]),
        ),
    ]
