# Generated by Django 5.2 on 2025-05-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0006_alter_tools_created_by_alter_tools_seria_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='counting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.department', verbose_name='department_tools'),
        ),
    ]
