# Generated by Django 5.2 on 2025-05-19 10:59

import worklog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0006_employee_id_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_code',
            field=models.CharField(max_length=10, unique=True, validators=[worklog.models.validate_national_code]),
        ),
    ]
