# Generated by Django 5.2 on 2025-05-28 10:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0007_remove_employee_employee_id_alter_employee_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltransferlog',
            name='returned_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tooltransferlog',
            name='taken_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
