# Generated by Django 5.2 on 2025-05-28 10:22

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0008_alter_tooltransferlog_returned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexitlog',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryexitlog',
            name='exit_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
