# Generated by Django 5.2 on 2025-05-28 10:50

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0009_alter_entryexitlog_entry_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalperson',
            options={'ordering': ('-centered_at',), 'verbose_name': 'ExternalPerson', 'verbose_name_plural': 'ExternalPerson'},
        ),
        migrations.RemoveField(
            model_name='externalperson',
            name='entered_at',
        ),
        migrations.RemoveField(
            model_name='externalperson',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='externalperson',
            name='centered_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalperson',
            name='exit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
