# Generated by Django 5.2 on 2025-05-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0009_entryexitlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PeopleCategory',
                'verbose_name_plural': 'PeopleCategory',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExternalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('compony', models.CharField(blank=True, max_length=100, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notex', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worklog.peoplecategory')),
            ],
            options={
                'verbose_name': 'ExternalPerson',
                'verbose_name_plural': 'ExternalPerson',
                'ordering': ('-entered_at',),
            },
        ),
    ]
