# Generated by Django 5.2 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0010_alter_externalperson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
