# Generated by Django 5.2 on 2025-06-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0011_toolcategory_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='peoplecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
