# Generated by Django 5.2 on 2025-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0012_remove_peoplecategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecategory',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
