# Generated by Django 5.2 on 2025-06-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0013_alter_peoplecategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
