# Generated by Django 5.2 on 2025-06-02 08:27

import worklog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0014_alter_department_title_alter_toolcategory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalperson',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[worklog.models.validate_national_code]),
        ),
    ]
