# Generated by Django 5.2 on 2025-06-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0015_alter_externalperson_national_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalperson',
            options={'ordering': ('-created_at',), 'verbose_name': 'ExternalPerson', 'verbose_name_plural': 'ExternalPerson'},
        ),
        migrations.RenameField(
            model_name='externalperson',
            old_name='centered_at',
            new_name='created_at',
        ),
    ]
